README.md

[CICD-1234](https://wpengine.atlassian.net/browse/CICD-1234)
While trying this action for the first time I didn't realize at first that the SSH Key needs to be passwordless, so I got into trouble connecting to the site. Adding this explicitly to the docs might reduce support contact.

Update the SSH Key generation description

---

action.yml
entrypoint.sh

This PR introduces a verification when the post script is set to run. The approach used is: 1. Check if the script exists in the remote host. If exists, run the version *in the remote host*, if it doesn't exists in the remote host, it will check if the script exists in the repository and rsync it to the remote host and execute.

Check if the script is in the remote host and copy if not

---

exclude.txt

[CICD-29](https://wpengine.atlassian.net/browse/CICD-29)
When adding all install files to a repository, the GHA build was failing due to rsync attempting to update the mu-plugin/wpe-cache-plugin subdirectories:
```
rsync: failed to set times on "/home/wpe-user/sites/dscicdtest1/wp-content/mu-plugins/wpe-cache-plugin": Operation not permitted (1)
rsync: failed to set times on "/home/wpe-user/sites/dscicdtest1/wp-content/mu-plugins/wpe-cache-plugin/css": Operation not permitted (1)
rsync: failed to set times on "/home/wpe-user/sites/dscicdtest1/wp-content/mu-plugins/wpe-cache-plugin/js": Operation not permitted (1)
rsync: failed to set times on "/home/wpe-user/sites/dscicdtest1/wp-content/mu-plugins/wpe-cache-plugin/js/components": Operation not permitted (1)
rsync: failed to set times on …
```

[CICD-29] Stop erroneous build failures due to attempt to rsync mu-plugin subdirectories

---

.github/workflows/e2e-deploy.yml
entrypoint.sh
tests/data/plugins/test-plugin/test-plugin.php
tests/data/post-deploy/test-plugin.sh

[CICD-47](https://wpengine.atlassian.net/browse/CICD-47)
Introduces a workflow that runs an end-to-end test of the action.
- Pull requests targeting `main` and pushes to `main` will trigger the workflow.
- Uses the local copy of the action. If a PR makes changes to the action, those changes are included in the test.
The objective of the test is to bump the version of a minimal WordPress plugin, deploy it to the remote, and validate that the remote plugin version was updated successfully. The test also resets the remote copy of the plugin to its pre-deploy state.
Commit d8dc96e introduces a breaking change to the action and results in the e2e test failing. The next commit reverts the breaking change and shows that the test passes again.

[CICD-47] Add a basic e2e test

---

README.md
exclude.txt

Sorry no ticket just a helpful bystander.
The purpose of this PR is to address 2 issues:
1. The new README documentation provides a working example to exclude deleting two files and a directory. The existing example is not helpful as it includes quote marks and appears to intend to exclude everything? After thorough testing, troubleshooting, and reaching out to support -- I was able to determine that quote marks are not actually supported.
2. The current exclude.txt wasn't actually excluding the wpe-cache-plugin, both the directory and the php file were being deleted. The included update appears to fix this issue.

Update Readme with working exclude example and ensure exclude.txt doesn't delete  wpe-cache-plugin

---

README.md

n/a
Adds a section to the README describing how we version so that users can make informed decisions about what version to bind to.

Add versioning information to README

---

.changeset/good-pears-play.md
entrypoint.sh

[CICD-77](https://wpengine.atlassian.net/browse/CICD-77)
Clearing page cache relies on WP CLI. When we call `wp page-cache flush`, the WP CLI bootstrap process loads all of WordPress, including active plugins and themes. If any of the loaded plugins or themes contain errors, those will cause the page cache clear to either fail or hang indefinitely. This results in a "failed" deploy status even if the code was successfully updated.
We don't need to load plugins and themes to successfully clear cache, so we can set flags to ignore them.

[CICD-77] Prevent plugin and theme conflicts from adversely affecting cache clear

---

.changeset/cdn-cache-clear.md
README.md
entrypoint.sh

[CICD-28](https://wpengine.atlassian.net/browse/CICD-28)
This PR adds CDN cache clearing functionality to the `CACHE_CLEAR` flag.
From e2e test logs:
```
debug1: Sending command: cd sites/ghae2e && sh tests/data/post-deploy/test-plugin.sh && wp --skip-plugins --skip-themes page-cache flush && wp --skip-plugins --skip-themes cdn-cache flush
debug1: mux_client_request_session: master session id: 2
New test plugin version: 0.0.2
Old test plugin version: 0.0.1
Success: Test plugin successfully updated from 0.0.1 to 0.0.2!
Success: Page Cache was flushed.
Success: CDN Cache was flushed.
```

Add CDN cache clearing to the CACHE_CLEAR flag

---

.github/workflows/e2e-deploy.yml

[CICD-68](https://wpengine.atlassian.net/browse/CICD-68)
This PR adds a cron schedule to to the e2e testing action, as well as Slack integration using a 3rd party action. This would allow us to monitor the health of the GHA by triggering our e2e tests every 5 minutes. On failure, it will notify the corresponding monitoring Slack channel #status-github-action.

[CICD-68] Add e2e cron schedule with Slack integration on failure

---

.github/workflows/e2e-deploy.yml

[CICD-68](https://wpengine.atlassian.net/browse/CICD-68)
Previous PR set Slack notifications to trigger on successes to test the integration. This PR sets Slack notifications to be triggered on failure as originally planned.

Set Slack notification to trigger on failure

---

.changeset/loud-penguins-flash.md
DEVELOPMENT.md
Dockerfile
Dockerfiles/Dockerfile

[CICD-24](https://wpengine.atlassian.net/browse/CICD-24)
Building and hosting image on WPE docker hub, then calling the hosted image instead of building it every time. 
**Original: Avg 11-14 seconds**
(Build Docker Container on the fly)
**New: 4 seconds :tada:** 
(Build Docker Container from Hosted Docker Image)
**NewNew: 1 second 🐎**
(Pull Docker Image directly from within action.yml)
**New SPLIT: 4 seconds ⏩**
(Build Docker Container from Hosted Docker Image, but split to add in exclude.txt and entrypoint script afterwards)
- We're going forward with the "Split" image approach - where base-stable is hosted in Dockerhub and imported as a directive into the main Dockerfile for the project. Additional directives and other frequently updated file inclusion are added below the image.  
* …

[CICD-24] Improve performance by utilizing pre-built Docker Image.

---

README.md

n/a
Resolves #69
Updates README examples to use the latest version of `actions/checkout`. The new version [uses the node16 runtime by default](https://github.com/actions/checkout/releases/tag/v3.0.0), which addresses the deprecation warnings mentioned in #69.

Update examples to use actions/checkout@v3

---

.github/actions/get-release-notes/action.yml
.github/actions/publish/publish.sh
.github/workflows/e2e-deploy.yml
.github/workflows/release.yml
tests/data/post-deploy/test-plugin.sh

[CICD-190](https://wpengine.atlassian.net/browse/CICD-190)
The `set-output` command is [deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/). This replaces all instances of `set-output` in our workflows.
Looking at each commit might make this easier to review.
Part 1: d3a4afc1efedbdf4334c7d47c9289e3ddd6f5fca - Places where the recommended alternative to `set-output` was a drop-in replacement.
Part 2: ce6a3f8604a9065a4f0b7b452689355f931c5194 - Refactors an instance where the drop-in replacement wouldn't work.
[CICD-190]: https://wpengine.atlassian.net/browse/CICD-190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CICD-190] Replace deprecated set output command

---

.changeset/orange-trees-bow.md
.gitignore
package-lock.json
package.json

[CICD-381](https://wpengine.atlassian.net/browse/CICD-381)
Here is where you should describe the problem you are solving, adding any fine details on the solution that might
otherwise not be recognizable for someone unfamiliar with the changes. Add some pictures if it helps.
Bump @changesets/cli > 2.26.2  to resolve the [semver vulnerability](https://github.com/advisories/GHSA-c2qf-rxjj-qqgw)
> 
> Versions of the package semver before 7.5.2 on the 7.x branch, before 6.3.1 on the 6.x branch, and all other versions before 5.7.2 are vulnerable to Regular Expression Denial of Service (ReDoS) via the function new Range, when untrusted user data is provided as a range.
> 
> **Patched versions**
> 7.5.2
> 6.3.1
> 5.7.2
[CICD-381]: https://wpengine.atlassian.net/browse/CICD-381?atlOrigin=eyJpIjoiNW …

[CICD-381] Bump @changesets/cli > 2.26.2 (resolve semver vuln)

---

.changeset/empty-stingrays-tie.md
README.md

[CICD-398](https://wpengine.atlassian.net/browse/CICD-398)
Here is where you should describe the problem you are solving, adding any fine details on the solution that might
otherwise not be recognizable for someone unfamiliar with the changes. Add some pictures if it helps.
Updating link to the exclude.txt, which was moved to https://github.com/wpengine/site-deploy/blob/main/exclude.txt
[CICD-398]: https://wpengine.atlassian.net/browse/CICD-398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CICD-398] Update exclude.txt link

---

.changeset/yellow-cows-live.md
action.yml

[CICD-757](https://wpengine.atlassian.net/browse/CICD-757)
Bump site deploy image version to 1.0.3.
[CICD-757]: https://wpengine.atlassian.net/browse/CICD-757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CICD-757] Bump site deploy image version

---

.github/workflows/release.yml
package.json

[NOJIRA]
When bumping versions during automated release, the package-lock file is not updated with new root package versions.
This PR adds a step to the release workflow to update package-lock as part of changeset versioning.
---
For reference, this same change was recently made in [site-deploy](https://github.com/wpengine/site-deploy/pull/33).

[NOJIRA] Add versioning step to update lock file

---

.github/actions/get-release-notes/action.yml

[CICD-496](https://wpengine.atlassian.net/browse/CICD-496)
Newline characters are not currently encoded properly when release notes are autogenerated.
This PR uses the `EOF` syntax (now recommended by GitHub) to handle encoding of the multi-line release note string.
For ease in testing locally, it is recommended for [`act`](https://github.com/nektos/act) to be installed:
```sh
brew install act
```
First, I added a test workflow called `test-get-release-notes.yml` with the following contents:
```yml
name: Test Get Release Notes
on: push
jobs:
test-get-release-notes:
runs-on: ubuntu-latest
steps:
- name: Checkout Repo
uses: actions/checkout@v4
- name: Setup Node.js 20.x
uses: actions/setup-node@v4
with:
node-version: 20.x
- name: Get release notes
id: notes
uses: …
```

[CICD-496] Fix autogenerated release notes

---

.github/workflows/e2e-deploy.yml

[CICD-497](https://wpengine.atlassian.net/browse/CICD-497)
Creates a queue when the e2e deploy testing workflow is triggered in an attempt to curb irrelevant notifications.
Otherwise, multiple instances of the e2e might try to access the test site at the same time, causing issues with validation of test results.
[CICD-497]: https://wpengine.atlassian.net/browse/CICD-497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CICD-497] Add concurrency queueing to e2e deploy workflow

---

.github/workflows/release.yml

[CICD-786](https://wpengine.atlassian.net/browse/CICD-786)
Upgrade action/setup-node to v4 for better Node 20 support (setup-node@v4 natively uses Node 20).
[CICD-786]: https://wpengine.atlassian.net/browse/CICD-786?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CICD-786] Upgrade actions/setup-node to v4

---

.github/workflows/e2e-deploy.yml

Dropping the e2e deploy test run to go once an hour. aka in Cron “At every 60th minute.”

[CICD-817] update cron

---

README.md

N/A
A couple of small updates to our Extended main.yml example.
1. Changed `--exclude-from=ignorefile.txt` to `--exclude-from=.deployignore` to match the filename referenced in the Deploy Options > FLAGS description.
2. Changed `--exclude=".*"` to `--exclude=.*`. After some testing done in [this build log](https://github.com/matthewselby/wpe-gitpush/actions/runs/10421612139/job/28864202832#step:4:8) the rsync `--exclude` option needs to be without quotes to be used in our Action Workflow. This also resolves #82

Update FLAGS formatting in README.md

---

README.md

n/a
Add additional documentation regarding quote usage in the FLAGS variable. Relates to the work that was done to fix flag parsing in https://github.com/wpengine/site-deploy/pull/32.

Update README to address quote usage in FLAGS

---

package-lock.json
package.json

[CICD-833](https://wpengine.atlassian.net/browse/CICD-833)
Sister PR to https://github.com/wpengine/site-deploy/pull/41, updating the same deps.
Resolves a vulnerability with a transitive dependency of @changesets/cli, which was patched in [@changesets/cli 2.7.10](https://github.com/changesets/changesets/releases/tag/%40changesets%2Fcli%402.27.10#:~:text=%231514%20962ab91%20Thanks%20%40nicoalonsop!%20%2D%20Update%20spawndamnit%20to%20fix%20cross%2Dspawn%20vulnerability).
Since @changesets/cli is a dev dependency for the repo, risk of releasing this change is low.
---
Offending transitive dependency tree before and after:
[CICD-833]: https://wpengine.atlassian.net/browse/CICD-833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CICD-883] Update @changesets/cli to 2.27.10

---

.changeset/nice-fans-buy.md
action.yml

[CICD-761](https://wpengine.atlassian.net/browse/CICD-761)
Fixes #91
Default exclude rules are now dynamically generated relative to `REMOTE_PATH`, if provided.
Implemented by https://github.com/wpengine/site-deploy/pull/42
[CICD-761]: https://wpengine.atlassian.net/browse/CICD-761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CICD-761] Bump wpengine/site-deploy to version 1.0.5

---

.github/workflows/e2e-deploy.yml

[CICD-428](https://wpengine.atlassian.net/browse/CICD-428)
Removes the notify step of our e2e workflow. The failures in this workflow have consistently been unrelated to the action itself and are therefore not actionable. Instead, they indicate an issue with some other service we depend on (GitHub, Docker Hub, SSH Gateway, WPE User Portal). These services are either out of our control or are already monitored in other ways.
**Bonus**: this gets rid of a dependency on `voxmedia/github-action-slack-notify-build`, which has been deprecated.
[CICD-428]: https://wpengine.atlassian.net/browse/CICD-428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CICD-428] Remove notify step from e2e deploy

---

package-lock.json
package.json

[CICD-818](https://wpengine.atlassian.net/browse/CICD-818)
The transitive `@babel/runtime` dependency was flagged as needing an update. This PR bumps the direct dependent `@changesets/cli` to the latest minor version.
Note that this is a dev dependency for building release change sets. No release/version bump of the action itself is required.
To confirm the functionality of `@changesets/cli` locally, I did the following:
- Ran `npx changesets add` and noted the new change set markdown file
- Ran `npm run version` and noted the version bump in package(-lock).json
[CICD-818]: https://wpengine.atlassian.net/browse/CICD-818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CICD-818] Bump @changesets/cli to version 2.29.3
